spring:
    datasource:
        url: jdbc:mysql://localhost:3306/fitnesstracker
        username: root
        password: secreta10
    jpa:
      generate-ddl: true
    hibernate:
        ddl-auto: create-drop
    generate-ddl: true
    show-sql: true